# Generated by Django 5.1.4 on 2025-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='blog_images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
